Repository EdLinker/edlinker-frontend, pull requests merged in 2021-05, with the labels that each got.

#48 Create custom theme
  angular.json
  src/app/modules/welcome/landing/components/landing-view/landing-view.component.html
  src/custom-theme.scss
Labels: desing / markup

#47 hotfix ssri vulnerability
  package-lock.json
Labels: hotfix, merge-candidate

#53 EditorConfig change config
  .editorconfig
Labels: merge-candidate

#50 Design
  src/app/app.module.ts
  src/app/modules/auth/auth-page/components/auth-page-view/auth-page-view.component.html
  src/app/modules/auth/auth-page/components/auth-page-view/auth-page-view.component.scss
  src/app/modules/shared/layout/layout.component.html
  src/app/modules/shared/layout/layout.component.scss
  src/app/modules/shared/layout/layout.component.ts
  src/app/modules/shared/shared-breadcrumbs/components/shared-breadcrumbs.component.html
  src/app/modules/shared/shared-breadcrumbs/components/shared-breadcrumbs.component.scss
  src/app/modules/shared/shared-breadcrumbs/components/shared-breadcrumbs.component.ts
  src/app/modules/shared/shared-breadcrumbs/index.ts
  src/app/modules/shared/shared-breadcrumbs/shared-breadcrumbs.module.ts
  src/app/modules/shared/shared-header/components/shared-header.component.html
  src/app/modules/shared/shared-header/components/shared-header.component.scss
  src/app/modules/shared/shared-post-card/components/shared-post/shared-post.component.html
  src/app/modules/shared/shared-post-card/components/shared-post/shared-post.component.scss
  src/app/modules/user-student/student-home/components/popup-post/popup-entry.component.ts
  src/app/modules/user-student/student-home/components/popup-post/popup-post.component.html
  src/app/modules/user-student/student-home/components/student-posts/student-posts.component.html
  src/app/modules/user-student/student-home/components/student-posts/student-posts.component.scss
  src/app/modules/user-teacher/teacher-post/components/teacher-create-post-form/teacher-create-post-form.component.scss
  src/assets/images/cats-flowers/cat0.png
  src/assets/images/cats-flowers/cat1.png
  src/assets/images/cats-flowers/cat2.png
  src/assets/images/cats-flowers/cat3.png
  src/assets/images/cats-flowers/cat4.png
  src/assets/images/cats-flowers/cat5.png
  src/assets/images/cats-flowers/houseplant0.png
  src/assets/images/cats-flowers/houseplant1.png
  src/assets/images/cats-flowers/houseplant2.png
  src/assets/images/logo.svg
  src/custom-theme.scss
  src/styles.scss
Labels: desing / markup, merge-candidate

#54 Hotfix popup img
  src/app/modules/user-student/student-home/components/popup-post/popup-post.component.html
  src/app/modules/user-student/student-home/components/popup-post/popup-post.component.scss
Labels: hotfix, merge-candidate
